#!/bin/bash

cd `dirname $BASH_SOURCE`

if [ -d ~/Library/Developer/Xcode/Templates/File\ Templates/Willhaben ]
then
	# remove templates that were there
	rm -rf ~/Library/Developer/Xcode/Templates/File\ Templates/Willhaben/
fi

# create directory for Xcode's custom templates
mkdir -p ~/Library/Developer/Xcode/Templates/File\ Templates/Willhaben

#overwrite cloned templates into newly created (or already present) directory
yes | cp -r *.xctemplate ~/Library/Developer/Xcode/Templates/File\ Templates/Willhaben
